[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/duoan/TorchCode/blob/master/templates/29_adam.ipynb)

# 🟠 Medium: Adam Optimizer

Implement the **Adam** optimizer from scratch.

### Signature
```python
class MyAdam:
    def __init__(self, params, lr=1e-3, betas=(0.9, 0.999), eps=1e-8): ...
    def step(self): ...
    def zero_grad(self): ...
```

### Algorithm (per parameter)
```
m = β1 * m + (1-β1) * grad
v = β2 * v + (1-β2) * grad²
m̂ = m / (1 - β1ᵗ)    # bias correction
v̂ = v / (1 - β2ᵗ)
p -= lr * m̂ / (√v̂ + ε)
```

In [1]:
# Install torch-judge in Colab (no-op in JupyterLab/Docker)
try:
    import google.colab
    get_ipython().run_line_magic('pip', 'install -q torch-judge')
except ImportError:
    pass


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.5/48.5 kB 1.6 MB/s eta 0:00:00


In [2]:
import torch

In [32]:
# ✏️ YOUR IMPLEMENTATION HERE

class MyAdam:
    def __init__(self, params, lr=1e-3, betas=(0.9, 0.999), eps=1e-8):
        self.params=params
        self.m=[torch.zeros_like(p) for p in params]
        self.v=[torch.zeros_like(p) for p in params]
        self.lr=lr
        self.eps=eps
        self.betas=betas
        self.t=0
    def step(self):
        for  i,p in enumerate(self.params):
          print(self.params[i])
          self.m[i]=self.betas[0]*self.m[i]+(1-self.betas[0])*p.grad
          self.v[i]= self.betas[1]*self.v[i]+(1-self.betas[1])*p.grad**2
          m_prime=self.m[i]/(1-self.betas[0])
          v_prime=self.v[i]/(1-self.betas[1])
          self.params[i]= self.params[i]- self.lr*m_prime/(torch.sqrt(v_prime)+self.eps)
          #print(self.lr*m_prime/(torch.sqrt(v_prime)+self.eps))
          print(self.params[i])
          #print(self.params[i].grad)

        pass  # update params using Adam rule

    def zero_grad(self):
        for i,p in  enumerate (self.params) :
          self.params[i].grad=torch.zeros_like(p.grad)
          #p.grad=torch.zeros_like(p.grad)
        pass  # zero all gradients

In [33]:
# 🧪 Debug
torch.manual_seed(0)
w = torch.randn(4, 3, requires_grad=True)
opt = MyAdam([w], lr=0.01)
for i in range(5):
    loss = (w ** 2).sum()
    loss.backward()
    opt.step()
    opt.zero_grad()
    print(f'Step {i}: loss={loss.item():.4f}')

tensor([[ 1.5410, -0.2934, -2.1788],
        [ 0.5684, -1.0845, -1.3986],
        [ 0.4033,  0.8380, -0.7193],
        [-0.4033, -0.5966,  0.1820]], requires_grad=True)
tensor([[ 1.5310, -0.2834, -2.1688],
        [ 0.5584, -1.0745, -1.3886],
        [ 0.3933,  0.8280, -0.7093],
        [-0.3933, -0.5866,  0.1720]], grad_fn=<SubBackward0>)


/tmp/ipykernel_2760/1203682157.py:27: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:492.)
  self.params[i].grad=torch.zeros_like(p.grad)


TypeError: zeros_like(): argument 'input' (position 1) must be Tensor, not NoneType

In [34]:
# ✅ SUBMIT
from torch_judge import check
check('adam')


🧪 Testing: Adam Optimizer (Medium)
──────────────────────────────────────────────────
tensor([[ 1.5410, -0.2934, -2.1788],
        [ 0.5684, -1.0845, -1.3986],
        [ 0.4033,  0.8380, -0.7193],
        [-0.4033, -0.5966,  0.1820]], requires_grad=True)
tensor([[ 1.5310, -0.2834, -2.1688],
        [ 0.5584, -1.0745, -1.3886],
        [ 0.3933,  0.8280, -0.7093],
        [-0.3933, -0.5866,  0.1720]], grad_fn=<SubBackward0>)
  ❌ [1/3] Parameters change after step
     Should change after step
tensor([[-1.1258, -1.1524, -0.2506, -0.4339],
        [ 0.8487,  0.6920, -0.3160, -2.1152],
        [ 0.3223, -1.2633,  0.3500,  0.3081],
        [ 0.1198,  1.2377,  1.1168, -0.2473],
        [-1.3527, -1.6959,  0.5667,  0.7935],
        [ 0.5988, -1.5551, -0.3414,  1.8530],
        [ 0.7502, -0.5855, -0.1734,  0.1835],
        [ 1.3894,  1.5863,  0.9463, -0.8437]], requires_grad=True)
tensor([[-1.1248, -1.1514, -0.2496, -0.4329],
        [ 0.8477,  0.6910, -0.3150, -2.1142],
        [ 0.3213, -1.

/tmp/ipykernel_2760/1203682157.py:27: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:492.)
  self.params[i].grad=torch.zeros_like(p.grad)
