[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/duoan/TorchCode/blob/master/templates/29_adam.ipynb)

# 🟠 Medium: Adam Optimizer

Implement the **Adam** optimizer from scratch.

### Signature
```python
class MyAdam:
    def __init__(self, params, lr=1e-3, betas=(0.9, 0.999), eps=1e-8): ...
    def step(self): ...
    def zero_grad(self): ...
```

### Algorithm (per parameter)
```
m = β1 * m + (1-β1) * grad
v = β2 * v + (1-β2) * grad²
m̂ = m / (1 - β1ᵗ)    # bias correction
v̂ = v / (1 - β2ᵗ)
p -= lr * m̂ / (√v̂ + ε)
```

In [ ]:
# Install torch-judge in Colab (no-op in JupyterLab/Docker)
try:
    import google.colab
    get_ipython().run_line_magic('pip', 'install -q torch-judge')
except ImportError:
    pass


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.5/48.5 kB 1.6 MB/s eta 0:00:00


In [ ]:
import torch

In [ ]:
# ✏️ YOUR IMPLEMENTATION HERE

class MyAdam:
    def __init__(self, params, lr=1e-3, betas=(0.9, 0.999), eps=1e-8):
        self.params=params
        self.m=[torch.zeros_like(p) for p in params]
        self.v=[torch.zeros_like(p) for p in params]
        self.lr=lr
        self.eps=eps
        self.betas=betas
        self.t=0
    def step(self):
        self.t+=1
        with torch.no_grad():

          for  i,p in enumerate(self.params):
            if p.grad is None:
              continue



            self.m[i]=self.betas[0]*self.m[i]+(1-self.betas[0])*p.grad
            self.v[i]= self.betas[1]*self.v[i]+(1-self.betas[1])*p.grad**2
            m_prime=self.m[i]/(1-self.betas[0]**self.t)
            v_prime=self.v[i]/(1-self.betas[1]**self.t)
            self.params[i]= self.params[i]- self.lr*m_prime/(torch.sqrt(v_prime)+self.eps)
            #print(self.lr*m_prime/(torch.sqrt(v_prime)+self.eps))
            print(self.params[i])
            #print(self.params[i].grad)

        pass  # update params using Adam rule

    def zero_grad(self):
        for i,p in  enumerate (self.params) :
          self.params[i].grad=torch.zeros_like(p.grad)
          #p.grad=torch.zeros_like(p.grad)
        pass  # zero all gradients

In [ ]:
# 🧪 Debug
torch.manual_seed(0)
w = torch.randn(4, 3, requires_grad=True)
opt = MyAdam([w], lr=0.01)
for i in range(5):
    loss = (w ** 2).sum()
    loss.backward()
    opt.step()
    opt.zero_grad()
    print(f'Step {i}: loss={loss.item():.4f}')

tensor([[ 1.5410, -0.2934, -2.1788],
        [ 0.5684, -1.0845, -1.3986],
        [ 0.4033,  0.8380, -0.7193],
        [-0.4033, -0.5966,  0.1820]], requires_grad=True)
tensor([[ 1.5310, -0.2834, -2.1688],
        [ 0.5584, -1.0745, -1.3886],
        [ 0.3933,  0.8280, -0.7093],
        [-0.3933, -0.5866,  0.1720]], grad_fn=<SubBackward0>)


/tmp/ipykernel_2760/1203682157.py:27: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:492.)
  self.params[i].grad=torch.zeros_like(p.grad)


TypeError: zeros_like(): argument 'input' (position 1) must be Tensor, not NoneType

In [ ]:
# ✅ SUBMIT
from torch_judge import check
check('adam')


🧪 Testing: Adam Optimizer (Medium)
──────────────────────────────────────────────────
tensor([[ 1.5410, -0.2934, -2.1788],
        [ 0.5684, -1.0845, -1.3986],
        [ 0.4033,  0.8380, -0.7193],
        [-0.4033, -0.5966,  0.1820]], requires_grad=True)
tensor([[ 1.5310, -0.2834, -2.1688],
        [ 0.5584, -1.0745, -1.3886],
        [ 0.3933,  0.8280, -0.7093],
        [-0.3933, -0.5866,  0.1720]], grad_fn=<SubBackward0>)
  ❌ [1/3] Parameters change after step
     Should change after step
tensor([[-1.1258, -1.1524, -0.2506, -0.4339],
        [ 0.8487,  0.6920, -0.3160, -2.1152],
        [ 0.3223, -1.2633,  0.3500,  0.3081],
        [ 0.1198,  1.2377,  1.1168, -0.2473],
        [-1.3527, -1.6959,  0.5667,  0.7935],
        [ 0.5988, -1.5551, -0.3414,  1.8530],
        [ 0.7502, -0.5855, -0.1734,  0.1835],
        [ 1.3894,  1.5863,  0.9463, -0.8437]], requires_grad=True)
tensor([[-1.1248, -1.1514, -0.2496, -0.4329],
        [ 0.8477,  0.6910, -0.3150, -2.1142],
        [ 0.3213, -1.

/tmp/ipykernel_2760/1203682157.py:27: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:492.)
  self.params[i].grad=torch.zeros_like(p.grad)


# Adam Optimizer

## Questions

### Warm-up
1. What problem does Adam solve compared to vanilla SGD?
2. Why do we maintain two moving averages (m and v) instead of one?
3. What do beta1 and beta2 control intuitively?

### Core Mechanics
4. Write the full Adam update equations (including bias correction).
5. Why do we divide by sqrt(v_hat) and not just v_hat?
6. What happens if eps is too large? Too small?
7. Why is bias correction needed? What goes wrong without it?

### Implementation-Level
8. Why must parameter updates be done inside torch.no_grad()?
9. What is the difference between p = p - update and p -= update?
10. Why do we check if p.grad is None?

### Deeper Understanding
11. How is Adam related to Momentum and RMSProp?
12. What happens if beta1 = 0 or beta2 = 0?
13. Why can Adam sometimes generalize worse than SGD?

### Practical + Research-Level
14. What is AdamW, and how is it different from Adam?
15. Why is weight decay in Adam tricky?
16. When would you prefer SGD over Adam?

### Edge Cases / Debugging
17. Your loss is not decreasing. What optimizer-related things would you check?
18. What happens if gradients are very sparse? Why does Adam help?
19. Why can Adam be unstable in some cases?

### Bonus
20. Can you derive Adam as a combination of momentum and adaptive learning rates?
21. Why is Adam considered a diagonal preconditioner?


## Answers

### Warm-up

**1. What problem does Adam solve compared to vanilla SGD?**  
Adam adapts the learning rate for each parameter individually using gradient statistics, leading to faster and more stable convergence.

**2. Why two moving averages (m and v)?**  
m tracks the mean of gradients (momentum), while v tracks the variance (scale). Together they give direction and adaptive step size.

**3. What do beta1 and beta2 control?**  
beta1 controls momentum smoothing. beta2 controls variance smoothing.

---

### Core Mechanics

**4. Full Adam update equations:**

```
m_t = beta1 * m_{t-1} + (1 - beta1) * g_t
v_t = beta2 * v_{t-1} + (1 - beta2) * g_t^2

m_hat = m_t / (1 - beta1^t)
v_hat = v_t / (1 - beta2^t)

theta = theta - lr * m_hat / (sqrt(v_hat) + eps)
```

**5. Why divide by sqrt(v_hat)?**  
Because v_hat estimates squared gradients. Taking square root brings it back to gradient scale.

**6. Effect of eps:**  
Too large makes Adam behave like SGD. Too small risks numerical instability.

**7. Why bias correction?**  
Moving averages start at zero and are biased early. Correction removes this bias.

---

### Implementation-Level

**8. Why torch.no_grad()?**  
To prevent updates from being tracked in the computation graph.

**9. Difference between p = p - update and p -= update?**  
p = p - update creates a new tensor. p -= update modifies the existing tensor in-place.

**10. Why check p.grad is None?**  
Some parameters may not receive gradients. This avoids errors.

---

### Deeper Understanding

**11. Relation to Momentum and RMSProp:**  
Momentum corresponds to m. RMSProp corresponds to v. Adam combines both.

**12. If beta1 = 0 or beta2 = 0:**  
beta1 = 0 removes momentum. beta2 = 0 removes adaptive scaling.

**13. Why worse generalization?**  
Adaptive learning rates can lead to sharper minima compared to SGD.

---

### Practical + Research-Level

**14. AdamW vs Adam:**  
AdamW decouples weight decay from gradient updates.

**15. Why weight decay tricky?**  
In Adam, L2 regularization interacts with adaptive scaling.

**16. When prefer SGD?**  
When generalization is more important, especially in large-scale vision tasks.

---

### Edge Cases / Debugging

**17. Loss not decreasing:**  
Check learning rate, gradients, bias correction, and parameter updates.

**18. Sparse gradients:**  
Adam handles sparse gradients better due to per-parameter scaling.

**19. Why unstable?**  
Large learning rates or poor beta settings can cause instability.

---

### Bonus

**20. Adam as momentum + adaptive LR:**  
Momentum provides direction. Variance scaling adjusts step size.

**21. Diagonal preconditioner:**  
Adam rescales each parameter independently, equivalent to a diagonal matrix scaling gradients.