[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/duoan/TorchCode/blob/master/templates/37_dpo_loss.ipynb)

# 🔴 Hard: DPO Loss

Implement the **Direct Preference Optimization** loss — the standard loss for LLM alignment.

$$\mathcal{L}_{\text{DPO}} = -\log \sigma\Big(\beta \big[\log\frac{\pi(y_w)}{\text{ref}(y_w)} - \log\frac{\pi(y_l)}{\text{ref}(y_l)}\big]\Big)$$

### Signature
```python
def dpo_loss(policy_chosen_logps, policy_rejected_logps,
             ref_chosen_logps, ref_rejected_logps, beta=0.1) -> Tensor:
    # All inputs: (B,) log-probabilities
    # Returns: scalar loss
```

In [1]:
# Install torch-judge in Colab (no-op in JupyterLab/Docker)
try:
    import google.colab
    get_ipython().run_line_magic('pip', 'install -q torch-judge')
except ImportError:
    pass


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.5/48.5 kB 3.6 MB/s eta 0:00:00


In [2]:
import torch
import torch.nn.functional as F

In [28]:
# ✏️ YOUR IMPLEMENTATION HERE

def dpo_loss(policy_chosen_logps, policy_rejected_logps,
             ref_chosen_logps, ref_rejected_logps, beta=0.1):
    eps=torch.tensor([10^-8])
    log_choosen=policy_chosen_logps/ref_chosen_logps
    log_rejected=policy_rejected_logps/ref_rejected_logps
    print(log_choosen, log_rejected)
    loss=-torch.log(torch.sigmoid(beta*(log_choosen-log_rejected))).mean()
    return loss
    pass  # -log(sigmoid(beta * (chosen_reward - rejected_reward)))

In [29]:
# 🧪 Debug
chosen = torch.tensor([0.0, 0.0])
rejected = torch.tensor([-5.0, -5.0])
ref_c = torch.tensor([-1.0, -1.0])
ref_r = torch.tensor([-1.0, -1.0])
print(dpo_loss(chosen, rejected, ref_c, ref_r, beta=0.1))
print('Loss:', dpo_loss(chosen, rejected, ref_c, ref_r, beta=0.1).item())

tensor([-0., -0.]) tensor([5., 5.])
tensor(0.9741)
tensor([-0., -0.]) tensor([5., 5.])
Loss: 0.9740769863128662


In [30]:
# ✅ SUBMIT
from torch_judge import check, hint
check('dpo_loss')


🧪 Testing: DPO (Direct Preference Optimization) Loss (Hard)
──────────────────────────────────────────────────
tensor([-0., -0.]) tensor([10., 10.])
  ❌ [1/5] Easy pair: small loss
     Easy pair loss too high: 1.3133
tensor([10.]) tensor([-0.])
  ❌ [2/5] Hard pair: large loss
     Hard pair loss too low: 0.3133
tensor([-2.9516,  0.2952,  0.6912,  1.9076], grad_fn=<DivBackward0>) tensor([-17.7396,  -2.0272,   1.8121,  -0.5904], grad_fn=<DivBackward0>)
  ✅ [3/5] Gradient flow (1.0ms)
tensor([ 3.8205, -0.3501,  3.0292]) tensor([-1.4093,  1.8177, -7.6831])
  ❌ [4/5] Mathematical correctness
     0.483546 vs 0.727598
tensor([-2.1425,  0.7275,  3.6518,  3.1226]) tensor([ 1.2660, -1.2708, -0.3765,  6.8298])
tensor([-2.1425,  0.7275,  3.6518,  3.1226]) tensor([ 1.2660, -1.2708, -0.3765,  6.8298])
  ✅ [5/5] Beta scaling (1.8ms)
──────────────────────────────────────────────────
  📊 2/5 tests passed.
  Keep going! Use hint("dpo_loss") if you're stuck.



In [27]:
hint("dpo_loss")


💡 Hint for DPO (Direct Preference Optimization) Loss:
   L = -log(sigmoid(beta * ((pi_chosen - ref_chosen) - (pi_rejected - ref_rejected)))). Mean over batch.

